update_fastlane

default_platform(:ios)

platform :ios do
	
	desc "Run the Xcode tests for the project."
	lane :tests do
		cocoapods()
		run_tests(
			workspace: ENV["WORKSPACE"],
			devices: ["iPhone 8"],
			scheme: ENV["SCHEME"],
			code_coverage: true
		)
	end
	
	desc "Gather code coverage stats for the project."
	desc "Project must be built first."
	lane :coverage do
		slather(
			scheme: ENV["SCHEME"],
			workspace: ENV["WORKSPACE"],
			proj: ENV["PROJ"],
			teamcity: true, 
			output_directory: "./fastlane/test_output/coverage"
		)
	end
	
	desc "Run pod lib lint on the project, using 3Squared's spec repo."
	lane :lint do
		pod_lib_lint(sources: ["3squared"], private: true)
	end
	
	desc "Push the project to the 3Squared spec repo."
	desc "This command is only valid on a clean repo where HEAD is a tagged commit on master."
	lane :release do		
		if sh("git", "tag", "-l", "--points-at", "HEAD").empty?
			UI.user_error!("You may only release tagged commits on master.")
		end
		
		ensure_git_branch
		ensure_git_status_clean
		lint
		pod_push(
			repo: "3squared",
			sources: ["3squared"]
		)
	end
end
