platform :ios, '11.0'

target 'PeakCoreDataExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PeakCoreData', :path => '../../'

end
